version: '3'
services: 
  backend:
    container_name: egg-bare-dev
    build: .
    hostname: egg-bare-dev
    restart: always
    environment:
      - EGG_SERVER_ENV=dev
      - EGG_MYSQL_DATABASE=
      - EGG_MYSQL_HOST=
      - EGG_MYSQL_PORT=
      - EGG_MYSQL_USERNAME=
      - EGG_MYSQL_PASSWORD=
      - EGG_REDIS_HOST=
      - EGG_REDIS_PORT=
      - EGG_REDIS_PASSWORD=
      - EGG_REDIS_DB=
      - EGG_ALINODE_APPID=
      - EGG_ALINODE_SECRET=
    ports:
      - 7002:80
    volumes:
      - /var/log/egg-bare-dev-logs:/root/logs